// 독립적인 화면 함수 검증. 브라우저나 실제 업무 저장소를 조작하지 않습니다.
const fs=require('fs'), path=require('path'), vm=require('vm'), assert=require('assert/strict');
const nodes=new Map();
const root={clientWidth:1400,querySelector(selector){if(!nodes.has(selector))nodes.set(selector,{innerHTML:'',value:'',hidden:false,children:[],style:{},classList:{toggle(){},add(){},remove(){}},appendChild(){},insertAdjacentHTML(){},showModal(){this.open=true},close(){this.open=false}});return nodes.get(selector);}};
const row={행정동명:'역삼1동',기준연월:'2025-12',metric_label:'유동인구 감소',is_risk_signal:true,has_enough_history:true,change_pct:-20,relative_change_pp:-10,risk_robust_z:3,explanation:'유동인구 감소 확인 후보'};
const BOOT={geometry:{강남구:{w:100,h:100,units:[{n:'역삼1동',d:'M0 0',cx:0,cy:0}]}},riskRows:[],startDate:'2025-01-01',endDate:'2025-12-31',months:['2025-12'],factorNames:[],factorShortNames:[],factorColors:[],weights:[25,25,20,15,15],thresholds:[25,50,75],accounts:[{id:'gangnam01',org:'강남구',admin:false}],missions:{},db1:{connected:true,runId:'run-1',assessment:[row],runs:[]}};
const triggered=[];
const context=vm.createContext({BOOT,root,listen(){},setStateValue(){},setTriggerValue:(name,data)=>triggered.push(data),document:{createElement(){return {}}},setTimeout,clearTimeout});
const ui=path.join(__dirname,'../ui');
vm.runInContext(['data.js','charts.js','responses.js','workspace.js','map.js','chat.js','bridge.js','dashboard.js'].map(f=>fs.readFileSync(path.join(ui,f),'utf8')).join('\n'),context);
const run=code=>vm.runInContext(code,context);
run('S.user=ACC[0]; S.city="강남구"; openRegionAnalysis("역삼1동")');
assert.equal(triggered.at(-1).action,'open_analysis');
assert.equal(triggered.at(-1).district,'역삼1동');
const key=JSON.stringify(['gangnam01','강남구','역삼1동','2025-12']);
BOOT.missions[key]={workflow_version:2,done:[0],analysis_evidence:[row],analysis_run_id:'run-1',reviews:[],connections:[],questions:[]};
assert(run('viewActualAnalysis()').includes('분석 근거 확인 완료'));
const before=triggered.length;
run('showRegionPreview("역삼1동")');
assert.equal(triggered.length,before,"팝업 조회는 서버 요청이 없어야 합니다");
assert(nodes.get("#region-dialog").open);
assert(nodes.get("#region-dialog-content").innerHTML.includes("상세 분석·업무 시작"));
assert(run("viewBriefing()").includes("신규 확인 후보"));
run('S.agentEnabled=false; send("왜 후보인가요?")');
assert.equal(triggered.length,before,'기본 질문은 서버/AI 요청을 보내면 안 됩니다');
assert(run('chatMenu()').includes('무엇을 도와드릴까요?'));
assert(run('viewActualOverview()').includes('district-tile'));
run('S.agentEnabled=true; send("왜 후보인가요?")');
assert.equal(triggered.at(-1).agent_enabled,true);
assert.equal(triggered.at(-1).action,'question');
assert(run('missionRecordsView()').includes('disabled'));
BOOT.missions[key].done=[0,1];
assert(!run('missionRecordsView()').includes('사업 검토" disabled'));
assert(run('viewActualOverview()').includes('우선 확인할 지역 1곳'));
assert(run('workflowReportView()').includes('disabled'));
BOOT.missions[key].done=[0,1,2];
BOOT.missions[key].connections=[{name:'교류 지원',status:'연결 승인',contact:'기관',actor:'gangnam01',created_at:'2026-10-02',note:'적합'}];
assert(run('missionRecordsView()').includes('사업 검토 완료 · 최종 보고서'));
assert(!run('missionRecordsView()').includes('연결 승인'));
assert(!run('workflowReportView()').includes('disabled'));
BOOT.db1.connected=false;
assert(run('viewActualOverview()').includes('후보 없음 판정과 구분'));
assert(!run('menuDef()[0].items.map(i=>i[0])').includes('data'));
console.log('PASS: 지역 클릭 → 저장된 분석, 질의 전달, 매칭/승인/보고 단계 및 미연결 표시');
